<?php
/**
 * Plugin Name: Sitemap Custom URL Generator
 * Plugin URI:  shahzaibalihassan@gmail.com
 * Description: This plugin works only for Yoast Seo Sitemap. So only use this plugin if you are using sitemap of Yoast SEO. The purpose of this plugin is that you can add any custom URL in the sitemap generated by Yoast SEO Plugin.
 * Version:     1.0.0
 * Author:      Shahzaib Ali Hassan
 * Author URI:  https://www.fiverr.com/users/shahzaib342
 * Text Domain: sitemap-custom-url-generator
 * License:     GPL2
 */

defined('ABSPATH') or die('Hey, get lost you silly human.');
if(file_exists(dirname(__FILE__)."/vendor/autoload.php"))
{
    require_once dirname(__FILE__)."/vendor/autoload.php";
}

use Inc\Base\Activate;
use Inc\Base\Deactivate;
use Inc\Base\CustomSitemap;
use Inc\Base\SaveUrl;

/**
 * The code that runs during plugin activation
 */
function activate_sitemap_custom_url_generator() {
    Activate::activate();
}
register_activation_hook( __FILE__, 'activate_sitemap_custom_url_generator' );

function deactiavte_sitemap_custom_url_generator()
{
    Deactivate::deactivate();
}
register_deactivation_hook(__FILE__,array('deactiavte_sitemap_custom_url_generator','activate'));

function so_wp_ajax_function(){
    SaveUrl::SaveUrl();
}
add_action( "wp_ajax_add_custom_url", "so_wp_ajax_function" );
add_action( "wp_ajax_nopriv_add_custom_url", "so_wp_ajax_function" );

function filter_wpseo_sitemap_index( $var ) {
    $sitemap = CustomSitemap::CustomSitemap();
    return $sitemap;
}
add_filter( 'wpseo_sitemap_index', 'filter_wpseo_sitemap_index', 10, 1 );

if(class_exists("Inc\\Init"))
{
    Inc\Init::register_services();
}

